@echo off
setlocal enabledelayedexpansion
chcp 65001 > nul

echo Генератор карты Minecraft для Windows
echo ====================================

REM Set paths with absolute paths
set "PROJECT_ROOT=%~dp0"
set "OVERVIEWER_PATH=%PROJECT_ROOT%overviwer"
set "MAP_BACKUP_PATH=%PROJECT_ROOT%map_backup"
set "MAP_OUTPUT_PATH=%PROJECT_ROOT%map"
set "TEXTURE_PATH=%PROJECT_ROOT%minecraft_assets\1.21.4_optifine\client.jar"
set "TEMP_CONFIG_PATH=%OVERVIEWER_PATH%\temp_config.py"

REM Check if running in build mode
set BUILD_MODE=false
if "%1"=="--build-mode" (
    set BUILD_MODE=true
    echo Запуск в режиме сборки...
)

REM Check if the map_backup directory has files
echo Проверка файлов мира...
dir /b "%MAP_BACKUP_PATH%\level.dat" >nul 2>&1
if %ERRORLEVEL% NEQ 0 (
    echo Ошибка: Файлы мира не найдены в директории map_backup.
    echo Убедитесь, что файл level.dat существует в %MAP_BACKUP_PATH%
    if "%BUILD_MODE%"=="true" (
        echo Это режим сборки, выход с ошибкой.
        exit /b 1
    ) else (
        echo Повторная попытка позже.
        timeout /t 60
        exit /b 0
    )
)

REM Set the number of processes to use (default to 1 if not set)
if not defined OVERVIEWER_PROCESSES (
    set OVERVIEWER_PROCESSES=1
)

REM Create the map directory if it doesn't exist
if not exist "%MAP_OUTPUT_PATH%" (
    mkdir "%MAP_OUTPUT_PATH%"
)

REM Check if texture file exists
if not exist "%TEXTURE_PATH%" (
    echo Ошибка: Файл client.jar не найден в %TEXTURE_PATH%
    echo Пожалуйста, создайте директорию minecraft_assets\1.21.4_optifine и поместите туда файл client.jar из .minecraft\versions\1.21.4\
    exit /b 1
)

REM Generate the Minecraft map using local Overviewer
echo Начало генерации карты с использованием %OVERVIEWER_PROCESSES% процессов...
echo Использование файлов мира из: %MAP_BACKUP_PATH%
echo Директория вывода: %MAP_OUTPUT_PATH%
echo Файл текстур: %TEXTURE_PATH%
echo Корневая директория проекта: %PROJECT_ROOT%

REM Check if overviewer.exe exists
if not exist "%OVERVIEWER_PATH%\overviewer.exe" (
    echo Ошибка: overviewer.exe не найден в %OVERVIEWER_PATH%
    exit /b 1
)

REM Create a temporary configuration file with absolute paths
echo Создание временного файла конфигурации...
(
    echo # Temporary Minecraft Overviewer configuration file
    echo # Generated by generate_map.bat
    echo import os
    echo.
    echo # Define absolute paths for textures, world, and output
    echo texturepath = r"%TEXTURE_PATH:\=\\%"
    echo world_path = r"%MAP_BACKUP_PATH:\=\\%"
    echo output_path = r"%MAP_OUTPUT_PATH:\=\\%"
    echo.
    echo # Print debug information
    echo print^(f"Texture path: {texturepath}"^)
    echo print^(f"World path: {world_path}"^)
    echo print^(f"Output path: {output_path}"^)
    echo.
    echo # Check if the texture file exists
    echo if not os.path.exists^(texturepath^):
    echo     print^(f"Warning: Texture file not found at {texturepath}"^)
    echo else:
    echo     print^(f"Texture file found at {texturepath}"^)
    echo.
    echo # Check if the world directory exists
    echo if not os.path.exists^(world_path^):
    echo     print^(f"Warning: World directory not found at {world_path}"^)
    echo else:
    echo     print^(f"World directory found at {world_path}"^)
    echo     # Check for level.dat
    echo     if os.path.exists^(os.path.join^(world_path, "level.dat"^)^):
    echo         print^(f"level.dat found in {world_path}"^)
    echo     else:
    echo         print^(f"Warning: level.dat not found in {world_path}"^)
    echo.
    echo # Define the world and output directory
    echo worlds["minecraft"] = world_path
    echo outputdir = output_path
    echo.
    echo # Default render
    echo renders["normalday"] = {
    echo     "world": "minecraft",
    echo     "title": "Дневной вид",
    echo     "rendermode": "smooth_lighting",
    echo     "dimension": "overworld",
    echo     "imgformat": "png",
    echo     "texturepath": texturepath
    echo }
    echo # Nether Renders
    echo renders["nether"] = {
    echo     "world": "minecraft",
    echo     "title": "Нижний мир",
    echo     "rendermode": "nether",
    echo     "dimension": "nether",
    echo     "imgformat": "png",
    echo     "texturepath": texturepath
    echo }
    echo.
    echo renders["end"] = {
    echo     "world": "minecraft",
    echo     "title": "Край",
    echo     "rendermode": "smooth_lighting",
    echo     "dimension": "end",
    echo     "imgformat": "png",
    echo     "texturepath": texturepath
    echo }
) > "%TEMP_CONFIG_PATH%"

REM Run Overviewer with the temporary configuration file
echo Запуск Overviewer...
cd /d "%OVERVIEWER_PATH%"
"%OVERVIEWER_PATH%\overviewer.exe" --config="%TEMP_CONFIG_PATH%" --processes=%OVERVIEWER_PROCESSES% --verbose

REM Check if generation was successful
if %ERRORLEVEL% NEQ 0 (
    echo Ошибка: Генерация карты не удалась.
    echo Проверка среды Python:
    python --version
    where python
    
    REM Create a simple index.html if map generation failed but we're in build mode
    if "%BUILD_MODE%"=="true" (
        echo Создание заглушки index.html...
        if not exist "%MAP_OUTPUT_PATH%" mkdir "%MAP_OUTPUT_PATH%"
        (
            echo ^<!DOCTYPE html^>
            echo ^<html^>
            echo ^<head^>
            echo     ^<title^>Карта Minecraft^</title^>
            echo     ^<meta charset="utf-8"^>
            echo     ^<style^>
            echo         body { font-family: Arial, sans-serif; text-align: center; margin-top: 50px; }
            echo     ^</style^>
            echo ^</head^>
            echo ^<body^>
            echo     ^<h1^>Карта Minecraft^</h1^>
            echo     ^<p^>Генерация карты не удалась. Пожалуйста, проверьте логи для получения дополнительной информации.^</p^>
            echo ^</body^>
            echo ^</html^>
        ) > "%MAP_OUTPUT_PATH%\index.html"
        echo Создан файл ошибки index.html
        REM Exit with success so the build can continue
        exit /b 0
    ) else (
        exit /b 1
    )
) else (
    echo Генерация карты завершена.
    echo Сгенерированные файлы:
    dir "%MAP_OUTPUT_PATH%"
    
    echo.
    echo Теперь вы можете открыть карту в браузере:
    echo file://%MAP_OUTPUT_PATH%/index.html
    
    REM Clean up temporary configuration file
    del "%TEMP_CONFIG_PATH%" 2>nul
)

endlocal 